# Generated by Django 3.2.2 on 2021-06-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0003_remove_bike_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(max_length=50)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
            ],
        ),
    ]
