# Generated by Django 3.2.2 on 2021-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name_plural': 'Bikes'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='bike',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
