# Generated by Django 3.2.2 on 2021-06-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20210608_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='has_sizes',
        ),
    ]
