# Generated by Django 3.2.2 on 2021-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20210611_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={},
        ),
        migrations.AddField(
            model_name='bike',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bike',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
